In [1]:
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize, RegexpTokenizer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
import json

In [2]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/arushijain/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [3]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/arushijain/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [4]:
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/arushijain/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [5]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/arushijain/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

# Structured data Preprocessing

In [24]:
structing = pd.DataFrame(pd.read_csv('argktest-snapshot.csv'))
structing = structing.dropna(subset=['input']).reset_index(drop=True)
print(structing.info())
structing

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2179 entries, 0 to 2178
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   index      2179 non-null   int64
 1   input      2179 non-null   object
 2   name       2179 non-null   object
 3   qty        2068 non-null   object
 4   range_end  2179 non-null   int64
 5   unit       1699 non-null   object
 6   comment    1428 non-null   object
dtypes: int64(2), object(5)
memory usage: 119.3+ KB
None

,index,input,name,qty,range_end,unit,comment
0,0,"1/2 large sliced sweet red onion , thinly",sweet red onion,1/2,0,NaN,"large sliced , thinly"
1,1,"6 fresh sliced ounces mushrooms ,",mushrooms,6,0,ounces,"fresh sliced ,"
2,2,4 corn tortillas,corn tortillas,4,0,NaN,NaN
3,3,1 9 refrigerated ounce package cheese tortelli...,cheese tortellini,1 9,0,ounce package,refrigerated ( )
4,4,2 fresh chopped tablespoons basil leaves,basil leaves,2,0,tablespoons,fresh chopped
...,...,...,...,...,...,...,...
2174,2174,3/4 powdered lb sugar ( Add more if icing is t...,sugar,3/4,0,lb,powdered ( Add more if icing is too thin )
2175,2175,1 teaspoon tender thyme leaves,tender thyme leaves,1,0,teaspoon,NaN
2176,2176,1 fresh chopped tablespoon parsley leaves,parsley leaves,1,0,tablespoon,fresh chopped
2177,2177,1 cup Russian salad dressing ( bottled is ok t...,Russian salad,1,0,cup,dressing ( bottled is ok too )
2178,2178,1 sprig celery leaves,celery leaves,1,0,sprig,NaN

In [25]:
print(structing.input[0])
structing.comment[0]

1/2 large sliced sweet red onion , thinly

'large sliced , thinly'

redundant words set

In [26]:
with open('measures_english.json', 'r') as file:
    measure = json.load(file)

measures = pd.DataFrame(measure["measures"])
measure = []
for i in measures.forms:
    measure += i
measure = set(measure)
measure

{' pkg.',
 'T',
 'bag',
 'barspoon',
 'bn',
 'bn.',
 'bottle',
 'bottled',
 'bottles',
 'box',
 'boxed',
 'boxes',
 'bsp',
 'bsp.',
 'bulb',
 'bunch',
 'bundle',
 'c',
 'c.',
 'can',
 'canned',
 'cans',
 'centiliter',
 'centilitre',
 'centimeter',
 'centimetre',
 'cl',
 'cl.',
 'clove',
 'cm',
 'cm.',
 'cms',
 'cms.',
 'contained',
 'container',
 'containers',
 'cp',
 'cube',
 'cup',
 'dash',
 'dollop',
 'drizzle',
 'drop',
 'ds',
 'ds.',
 'fifth',
 'fl oz',
 'fl oz.',
 'fl qt',
 'fl qt.',
 'fl. oz',
 'fl. oz.',
 'fl. qt',
 'fl. qt.',
 'fluid ounce',
 'g',
 'g.',
 'gal',
 'gal.',
 'gallon',
 'generous',
 'gill',
 'gl',
 'gl.',
 'gm',
 'gm.',
 'gr',
 'gr.',
 'gram',
 'gramme',
 'handful',
 'head',
 'heaping',
 'hooker',
 'inch',
 'inches',
 'jar',
 'jarred',
 'jars',
 'jigger',
 'kg',
 'kg.',
 'kgr',
 'kgr.',
 'kilogram',
 'kilogramme',
 'l',
 'l.',
 'lb',
 'lb.',
 'leaf',
 'lf',
 'lf.',
 'link',
 'liter',
 'litre',
 'mg',
 'mg.',
 'mgr',
 'mgr.',
 'miligram',
 'mililiter',
 'milligram',
 'milligramme',
 'milliliter',
 'millilitre',
 'millimeter',
 'millimetre',
 'ml',
 'ml.',
 'mm',
 'mm.',
 'ounce',
 'oz',
 'oz.',
 'p',
 'p.',
 'package',
 'packaged',
 'packages',
 'packed',
 'packet',
 'packets',
 'part',
 'pc',
 'pc.',
 'pcs',
 'pcs.',
 'piece',
 'pinch',
 'pint',
 'pk',
 'pk.',
 'pkg',
 'pkgs',
 'pkgs.',
 'pkt',
 'pkt.',
 'pn',
 'pn.',
 'pound',
 'pt',
 'pt.',
 'q',
 'q.',
 'qt',
 'qt.',
 'quart',
 'scr',
 'scr.',
 'scruple',
 'sheet',
 'shot',
 'sht',
 'sht.',
 'sli',
 'sli.',
 'slice',
 'smdg',
 'smdg.',
 'smidgeon',
 'snit',
 'spg',
 'spg.',
 'splash',
 'sprig',
 'sprinkle',
 'stalk',
 'stick',
 't',
 't.',
 'tablespoon',
 'tb',
 'tb.',
 'tbl',
 'tbl.',
 'tblsp',
 'tblsp.',
 'tbs',
 'tbs.',
 'tbsp',
 'tbsp.',
 'tbsps',
 'tbsps.',
 'tcp',
 'tcp.',
 'tea-cup',
 'teacup',
 'teaspoon',
 'tin',
 'to taste',
 'traditional fifth',
 'tsp',
 'tsp.',
 'tsps',
 'tsps.',
 'twig',
 'twist',
 'twst',
 'twst.',
 'unit'}

In [27]:
names = set(structing['name'].copy().tolist())
names

{'Amaretto',
 'Amarula liqueur',
 'American cheese',
 'Asian sesame oil',
 'Barilla Gluten Free Penne',
 'Cajun seasoning',
 'Catalina salad dressing',
 'Cheddar cheese',
 'Cheddar/Monterey Jack cheese blend',
 'Chinese five spice powder',
 'Chinese mushrooms',
 'Clamato juice',
 'Cool Whip Topping',
 'Cotija cheese',
 'Dijon mustard',
 'English cucumber',
 'English cucumbers',
 'French',
 'French bread',
 'Greek yogurt',
 'Italian bread',
 'Italian herb seasoning',
 'Italian parsley',
 'Italian salad dressing',
 'Italian sausage',
 'Italian seasoning',
 'Kahlua',
 'Knorr vegetable soup mix',
 'Licor',
 'Lime Wedge',
 'Mexican-style corn',
 'Minute Rice',
 'Monterey Jack cheese',
 'Morton nature seasons seasoning blend',
 'Oreo cookie crumbs',
 'Parmesan Cheese',
 'Parmesan cheese',
 'Parmigiano Reggiano cheese',
 'Ritz cracker crumbs',
 'Russian salad',
 'Seasoned Salt',
 'Sichuan peppercorns',
 'Signature Secrets culinary thickener',
 'Spanish onions',
 'Swiss cheese',
 'Tabasco sauce',
 'Tang orange',
 'Texas toast bread',
 'Thai chiles',
 'Thai fish sauce',
 'Thai sweet chili sauce',
 'Velveeta cheese',
 'Wolf brand chili',
 'Worcestershire sauce',
 'acorn squash',
 'active yeast',
 'aji nori',
 'ale',
 'all fruit pineapple preserves',
 'all-purpose flour',
 'allspice',
 'allspice berries',
 'almond essence',
 'almonds',
 'aluminum foil',
 'ammonium chloride',
 'anchovies',
 'angel hair pasta',
 'anise oil',
 'anise seed',
 'apple',
 'apple cider vinegar',
 'apple juice',
 'apple pie filling',
 'apples',
 'apricot',
 'apricot preserves',
 'artichoke hearts',
 'artichokes',
 'asafoetida powder',
 'asian peanut oil',
 'aubergine',
 'avocado',
 'avocados',
 'baby bok choy',
 'baby capers',
 'baby carrots',
 'baby corn',
 'baby potatoes',
 'baby red potato',
 'baby rocket',
 'bacon',
 'baharat spice',
 'baking potatoes',
 'baking powder',
 'baking soda',
 'balsamic vinegar',
 'bamboo shoot',
 'banana',
 'bananas',
 'barbecue sauce',
 'basil',
 'basil leaves',
 'basil pesto',
 'basmati rice',
 'bay leaves',
 'bbq chicken',
 'bean sprouts',
 'beans',
 'beans chili',
 'beef',
 'beef beef roast',
 'beef bouillon cubes',
 'beef bouillon powder',
 'beef brisket',
 'beef broth',
 'beef chuck roast',
 'beef eye round',
 'beef flank steak',
 'beef liver',
 'beef round roast',
 'beef round steak',
 'beef steak',
 'beef steak spices',
 'beef stew meat',
 'beef stock',
 'beef tenderloin',
 'beefsteak tomato',
 'beer',
 'bell pepper',
 'berbere',
 'bermuda onion',
 'bibb lettuce Boston lettuce',
 'bittersweet chocolate',
 'bittersweet chocolate bittersweet',
 'black',
 'black bean sauce',
 'black beans',
 'black olives',
 'black pepper',
 'black peppercorn',
 'black peppercorns',
 'blue cheese',
 'blue curacao',
 'blueberries',
 'borlotti beans',
 'bourbon vanilla extract',
 'brandy',
 'bread',
 'bread crumbs',
 'bread flour',
 'breadcrumb',
 'breadcrumbs',
 'brisket',
 'broccoli',
 'broccoli , florets',
 'broth oxtails',
 'brown rice',
 'brown stock',
 'brown sugar',
 'burrito-size tortillas',
 'butter',
 'butter cubes',
 'butter margarine',
 'butter oil',
 'buttermilk',
 'butternut squash',
 'butterscotch chips',
 'cabbage',
 'cacao powder',
 'caciocavallo',
 'cake flour',
 'campbell',
 'cannellini beans',
 'cannellini white kidney beans',
 'canola oil',
 'cantaloupe',
 'capellini',
 'capers',
 'capicola',
 'caramel ice cream topping',
 'caramel sauce',
 'caraway seeds',
 'cardamom pods',
 'cardamom powder',
 'carrot',
 'carrot juice',
 'carrots',
 'cashew nuts',
 'cashews',
 'caster sugar',
 'catsup',
 'cauliflower',
 'cayenne',
 'cayenne pepper',
 'cayenne powder',
 'celery',
 'celery leaves',
 'celery ribs',
 'celery salt',
 'celery seed',
 'celery seeds',
 'champagne',
 'chanterelle mushrooms',
 'chard leaves',
 'chartreuse liqueur',
 'cheddar cheese',
 'cheese',
 'cheese cheddar jack',
 'cheese food',
 'cheese tortellini',
 'cherries',
 'cherry pie filling',
 'cherry tomatoes',
 'chestnuts',
 'chicken',
 'chicken bouillon',
 'chicken bouillon granules',
 'chicken bouillon powder',
 'chicken breast',
 'chicken breast halves',
 'chicken breasts',
 'chicken breasts steaks',
 'chicken broth',
 'chicken livers',
 'chicken seasoning',
 'chicken stock',
 'chicken thighs',
 'chicken tips',
 'chickpea flour',
 'chickpeas',
 'chile',
 'chile pepper',
 'chili',
 'chili oil',
 'chili paste garlic',
 'chili pepper flakes',
 'chili powder',
 'chili sauce',
 'chili seasoning mix',
 'chinese rice wine',
 'chipotle chile pepper adobo sauce',
 'chipotle chiles',
 'chipotle peppers adobo sauce',
 'chives',
 'chocolate',
 'chocolate chips',
 'chocolate liqueur',
 'chocolate pellets',
 'chocolate ripple biscuits',
 'chorizo sausage',
 'chorizo sausages',
 'chow mein noodles',
 'cider vinegar',
 'cilantro',
 'cilantro leaf',
 'cilantro leaves',
 'cinnamon',
 'clam',
 'clam juice',
 'clams',
 'clams juice',
 'clarified butter',
 'cleaned crawfish',
 'clove',
 'cloves',
 'cocoa',
 'cocoa powder',
 'coconut',
 'coconut cream',
 'coconut milk',
 'coconut oil',
 'coffee',
 'cognac',
 'collard greens substitute greens',
 'colored candy sprinkles',
 'confectioners sugar',
 'cooking oil',
 'cooking spray',
 'coriander',
 'coriander leaves',
 'coriander powder',
 'coriander seeds',
 'corn',
 'corn chips',
 'corn kernel',
 'corn kernels',
 'corn niblets',
 'corn oil',
 'corn oil meat',
 'corn tortillas',
 'corn tostadas',
 'cornflour',
 'cornmeal',
 'cornstarch',
 'cornstarch paste',
 'cottage cheese',
 'crabmeat',
 'cracker crumb',
 'cranberry sauce',
 'cream',
 'cream celery soup',
 'cream cheese',
 'cream cheese chives onions',
 'cream chicken soup water',
 'cream of chicken soup',
 'cream of mushroom soup',
 'cream wheat',
 'cream yogurt',
 'creamy peanut butter',
 'creme fraiche',
 'cremini mushrooms',
 'crescent rolls',
 'cucumber',
 'cucumbers',
 'cumin',
 'cumin powder',
 'cumin seeds',
 'currants',
 'curry',
 'curry leaves',
 'curry powder',
 'custard powder',
 'daikon radishes',
 'dark rum',
 'dates',
 'dill',
 'dinner rolls',
 'double-acting baking powder',
 'egg',
 'egg noodles',
 'egg white',
 'egg whites',
 'egg yolks',
 'eggplant',
 'eggplants',
 'eggs',
 'eggs whites yolks',
 'enchilada sauce',
 'english mustard paste',
 'extra chicken breast',
 'extra egg egg',
 'extra flour',
 'extra olive oil',
 'extra virgin olive oil',
 'extra-virgin olive oil',
 'fairtrade brazil nut',
 'fajita seasoning',
 'fajita seasoning mix',
 'fajita-size flour tortillas',
 'fennel',
 'fennel bulb',
 'fennel seed',
 'fennel seeds',
 'fenugreek',
 'fenugreek methi',
 'fenugreek seeds',
 'feta cheese',
 'fettuccine',
 'fiddlehead ferns',
 'figs',
 'fillets',
 'fillets salmon',
 'firm tofu',
 'firm white fish fillets',
 'fish fillet',
 'fish fillets',
 'fish sauce',
 'fish stock',
 'flake coconut',
 'flank steaks',
 'flat leaf parsley cilantro',
 'flax seed',
 'flax seeds',
 'flour',
 'flour tortillas',
 'fuji apple',
 'fusilli',
 'garam masala',
 'garam masala powder cinnamon black pepper',
 'garbanzo beans',
 'garlic',
 'garlic garlic',
 'garlic oil',
 'garlic paste',
 'garlic powder',
 'garlic salt',
 'garlic-infused olive oil',
 'gelatin',
 'ghee',
 'ghee oil',
 'ginger',
 'ginger powder',
 'ginger root',
 'gingerroot',
 'gluten',
 'gluten-free hoisin sauce',
 'goat cheese',
 'gorgonzola',
 'goya whole kernel golden corn',
 'grain bread',
 'grain mustard',
 'grain rice',
 'grain tortillas',
 'grape tomatoes',
 'green asparagus',
 'green beans',
 'green bell pepper',
 'green cardamom',
 'green chile peppers',
 'green chiles',
 'green chili peppers',
 'green chilies',
 'green enchilada sauce',
 'green olives',
 'green onion',
 'green onions',
 'green pepper',
 'green peppers',
 'green red bell pepper',
 'green salad',
 'guajillo chilies',
 'half-and-half',
 'ham',
 'hamburger',
 'hamburger buns',
 'head cabbage',
 'head cauliflower',
 'heads savoy cabbage',
 'hearts palm',
 'heavy cream',
 'heavy whipping cream',
 'heineken beer',
 'hoagie rolls',
 'hoisin sauce',
 'hominy',
 'honey',
 'honey maple syrup',
 'honey peanuts',
 'horseradish',
 'hot dog buns',
 'ice',
 'ice cream',
 'ice water',
 'iceberg lettuce',
 'icing sugar',
 'instant coffee granules',
 'instant oats',
 'instant rice',
 'irish cream',
 'isopropyl alcohol',
 'italian bread pizza crust',
 'italian seasoning',
 'jaggery',
 'jalapeno',
 'jalapeno pepper',
 'jalapeno peppers',
 'jalapenos',
 'jasmine rice',
 'jicama',
 'jiggers banana liqueur',
 'kaffir lime leaves',
 'kalamata olive',
 'kalamata olives',
 'kale',
 'ketchup',
 'ketjap manis',
 'kidney beans',
 'kirby cucumbers',
 'kosher salt',
 'kudzu',
 'lamb',
 'lamb chops',
 'lard',
 'lasagna',
 'lasagna noodles',
 'leaf lettuce',
 'leaf parsley',
 'leaves lettuce',
 'leaves spinach baby',
 'leek',
 'leg lamb',
 'leg of lamb',
 'lemon',
 'lemon cucumbers',
 'lemon curd',
 'lemon grass',
 'lemon juice',
 'lemon peel',
 'lemon pepper',
 'lemon rind',
 'lemon zest',
 'lemongrass',
 'lemons',
 'lentils',
 'lettuce',
 'lettuce leaf',
 'light soy sauce',
 'lima beans',
 'lime',
 'lime juice',
 'lime juice base',
 'lime wedge',
 'lime wedges',
 'lime zest',
 'limes',
 'limes juice zest',
 'linguine',
 'long grain white rice',
 'macadamia nut oil',
 'mace',
 'maggi seasoning sauce',
 'maine lobsters',
 'mango',
 'mangoes',
 'maple syrup',
 'margarine',
 'margarine butter',
 'marinara sauce',
 'marjoram',
 'mascarpone',
 'mascarpone cheese',
 'mayonnaise',
 'mayonnaise food',
 'meat tenderizer',
 'mexican chocolate',
 'mexican tomatoes',
 'mild Italian turkey sausage',
 'mild indian curry powder',
 'milk',
 'milo',
 'miniature marshmallows',
 'mint',
 'mint leaf',
 'mint leaves',
 'minute maid lemonade',
 'mirin',
 'miso',
 'miso paste',
 'mixed fruit',
 'mixed salad green',
 'mixed spice',
 'molasses',
 'monterey jack cheese',
 'monterey jack pepper cheese',
 'mostaccioli pasta',
 'mozzarella cheese',
 'mushroom',
 'mushrooms',
 'mustard',
 'nanami togarashi',
 'napa cabbage',
 'nigella seeds',
 'nori',
 'nutmeg',
 'oat bran',
 'oatmeal',
 'oats',
 'oil',
 'olive oil',
 'olive oil garlic',
 'olives',
 'onion',
 'onion flakes',
 'onion powder',
 'onion soup mix',
 'onion vegetable',
 'onions',
 'onions onions',
 'orange',
 'orange juice',
 'orange rind',
 'orange zest',
 'oregano',
 'oregano leaves',
 'organic butternut squash',
 'organic tomato sauce',
 'oyster sauce',
 'pak choi',
 'palm sugar',
 'pancetta',
 'panko bread crumbs',
 'paper baking',
 'pappardelle pasta',
 'paprika',
 'parmesan cheese',
 'parmigiano-reggiano cheese',
 'parmigiano-reggiano cheese table',
 'parsley',
 'parsley flakes',
 'parsley leaves',
 'pasta',
 'peaches',
 'peanut butter',
 'peanut oil',
 'peanuts',
 'pearl tapioca',
 'peas',
 'peas carrots',
 'penne',
 'penne rigate',
 'pepper',
 'pepper sauce',
 'peppercorn',
 'peppercorns',
 'pepperjack cheese',
 'pepperoni',
 'pepperoni sausage',
 'phyllo dough',
 'phyllo pastry',
 'phyllo pastry dough',
 'pickle',
 'pillsbury original',
 'pimento stuffed olive',
 'pimiento',
 'pine nut oil',
 'pine nuts',
 'pine nuts Pecans',
 'pineapple',
 'pineapple chunks',
 'pineapple cream cheese spread',
 'pineapple juice',
 'pint ricotta cheese',
 'pizza crust',
 'plain yogurt',
 'plum tomatoes',
 'plums',
 'poblano pepper',
 'poblano peppers',
 'pod star anise',
 'polenta',
 'pomegranate',
 'pomegranate juice',
 'popcorn',
 'poppy seeds',
 'porcini mushrooms',
 'pork',
 'pork back ribs',
 'pork barbecue sauce',
 'pork chops',
 'pork hocks',
 'pork loin roast',
 'pork pork',
 'pork ribs',
 'pork sirloin',
 'pork stock',
 'pork tenderloin',
 'pork tenderloins',
 'porridge oats',
 'port wine',
 'portobello mushroom caps',
 'potato',
 'potato chips',
 'potatoes',
 'powder',
 'prawns',
 'prepared horseradish',
 'prosciutto',
 'puerto rican seasoning salt',
 'puff pastry',
 'pumpkin',
 'pumpkin pie spice',
 'pumpkin puree pumpkin pie',
 'quinoa flakes',
 'radishes',
 'raisin',
 'raisins',
 'raisins currants',
 'raspberries',
 'raspberry jam',
 'real maple syrup',
 'red Thai chile',
 'red beans',
 'red bell pepper',
 'red bell peppers',
 'red cabbage',
 'red capsicum',
 'red capsicums',
 'red chili pepper flakes',
 'red chili powder',
 'red currant jelly',
 'red curry paste',
 'red dates',
 'red food coloring',
 'red fruit',
 'red grapes',
 'red jalapeno chile',
 'red miso paste',
 'red onion',
 'red onions',
 'red pepper',
 'red pepper cayenne',
 'red pepper flakes',
 'red peppers',
 'red potatoes',
 'red wine',
 'red wine vinegar',
 'refried beans',
 'relish sandwich spread',
 'reynolds aluminum foil',
 'rice',
 'rice bubbles',
 'rice flour',
 'rice noodles',
 'rice vinegar',
 'rice wine vinegar',
 'ricotta cheese',
 'rigatoni pasta',
 'rind',
 'rock lobster meat',
 'rolled oats',
 'roma tomato',
 'roma tomatoes',
 'romaine lettuce leaves',
 'romano cheese',
 'rosemary',
 'round steaks',
 'rum',
 'russet potatoes',
 'russet potatoes yukon gold potatoes',
 'rutabaga',
 'saffron',
 'saffron thread',
 'saffron threads',
 'sage',
 'sake',
 'salad greens',
 'salad shrimp',
 'salmon',
 'salmon fillets',
 'salmon steaks',
 'salsa',
 'salt',
 'salt Pepper',
 'salt black pepper',
 'salt pepper',
 'salt pepper nutmeg',
 'salt pork',
 'sambal oelek',
 'sauce',
 'sausage',
 'sausage pork',
 'sausages',
 'scallion',
 'scallions',
 'scallops',
 'sea salt',
 'seafood seasoning Bay Seasoning',
 'seasoning blend',
 'seasoning salt',
 'seeds ajwain',
 'seitan',
 'self-raising flour',
 'semolina flour',
 'serrano chile pepper',
 'serrano chili',
 'serrano chili peppers',
 'sesame oil',
 'sesame seeds',
 'shallot',
 'shallot salt',
 'shallots',
 'shark steaks',
 'sherry',
 'sherry wine',
 'sherry wine vinegar',
 'shiitake mushroom',
 'shiitake mushrooms',
 'shrimp',
 'sirloin steaks',
 'skim milk',
 'skirt steaks steak',
 'snow peas',
 'soft brown sugar',
 'soft goat cheese',
 'soft margarine',
 'soup water',
 'soy sauce',
 'soybeans',
 'soymilk',
 'spaghetti',
 'spaghetti sauce',
 'spaghetti squash',
 'spike seasoning',
 'spinach',
 'spinach leaves',
 'spinach pasta',
 'sponge cake',
 'spot prawns',
 'spring onions',
 'star anise',
 'starburst decorative candies',
 'steaks',
 'stir fry vegetables',
 'strawberries',
 'strawberry',
 'stubby beer all',
 'sugar',
 'sugar cream',
 'sugar snap peas',
 'sugar substitute',
 'sultana',
 'sultanas',
 'sunflower seeds',
 'sweet Italian pepper',
 'sweet Italian sausage',
 'sweet chili sauce',
 'sweet corn',
 'sweet green pepper',
 'sweet onion',
 'sweet paprika',
 'sweet peas',
 'sweet pepper red yellow',
 'sweet potato',
 'sweet potatoes',
 'sweet red onion',
 'swiss cheese',
 'syrup',
 'szechwan pepper',
 'taco seasoning mix',
 'tahini',
 'tahini sesame paste',
 'tamarind paste',
 'tandoori curry paste',
 'tapioca flour',
 'tarragon',
 'tarragon vinegar',
 'tender thyme leaves',
 'tequila',
 'teriyaki sauce',
 'texturized vegetable protein',
 'thick rice stick noodles',
 'thyme',
 'tilapia fillets',
 'tofu',
 'tomato',
 'tomato basil garlic seasoning',
 'tomato juice',
 'tomato passata',
 'tomato paste',
 'tomato sauce',
 'tomatoes',
 'tomatoes juice',
 'toothpicks water',
 'top round beef',
 'tortilla chips',
 'tortillas',
 'triple sec',
 'turbinado sugar',
 'turkey',
 'turkey breast halves',
 'turmeric',
 'turmeric powder',
 'vanilla',
 'vanilla bean',
 'vanilla bean ice cream',
 'vanilla ice cream',
 'vanilla pod',
 'vanilla sugar',
 'vanilla wafers',
 'vanilla yogurt',
 'veal',
 'veal escalopes',
 'vegetable broth',
 'vegetable oil',
 'vegetable stock',
 'veggie crumbles',
 'venison heart',
 'vermicelli spaghetti',
 'vinaigrette',
 'vinegar',
 'vodka',
 'walnut',
 'walnuts',
 'water',
 'water chestnuts',
 'watercress',
 'waterview dark rum',
 'wheat breadcrumbs',
 'wheat flour',
 'wheat noodles',
 'wheat tortillas',
 'whipped cream',
 'whipping cream',
 'whiskey',
 'white beans',
 'white bread',
 'white button mushrooms',
 'white onion',
 'white onions',
 'white pearl onion',
 'white pepper',
 'white peppercorns',
 'white pita breads',
 'white poppy seeds',
 'white rice',
 'white sugar',
 'white vinegar',
 'white wine',
 'whole',
 'wine',
 'wine vinegar',
 'wonton wrappers',
 'wooden skewers',
 'wrap',
 'yeast',
 'yeast extract spread',
 'yellow cherry tomato',
 'yellow cornmeal',
 'yellow curry powder',
 'yellow onion',
 'yellow onions',
 'yellow sweet pepper',
 'yellow tomatoes',
 'yoghurt',
 'yogurt',
 'yukon gold potatoes',
 'ziti pasta',
 'zucchini',
 'zucchinis'}

In [28]:
def red(text):

    # Tokenization
    tokens = word_tokenize(text)

    # Convert to lowercase
    tokens = [token.lower() for token in tokens]

    # Remove punctuation and non-alphanumeric characters
    tokens = [token for token in tokens if token.isalpha()]

    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    tokens = [token for token in tokens if token not in stop_words]

    # Stemming
    lemmer = WordNetLemmatizer()

    tokens = [lemmer.lemmatize(token) for token in tokens]

    # Remove units
    tokens_ = [token for token in tokens if token not in measure]

    # Remove 1, 2 and 3 worded food names
    tokens = []
    for i in range(len(tokens_)-2):
        if tokens_[i] not in names and " ".join([tokens_[i], tokens_[i+1]]) not in names and " ".join([tokens_[i], tokens_[i+1], tokens_[i+2]]) not in names:
            tokens.append(tokens_[i])

    return tokens

In [47]:
comments = structing.comment.copy()
comments = comments.dropna().reset_index(drop=True)
comments = comments.apply(red)
redund = []
for i in comments:
    if i:
        redund += i
redund = set(redund)
redund

{'according',
 'add',
 'adjust',
 'another',
 'approximate',
 'asadero',
 'baguette',
 'bean',
 'beaten',
 'bias',
 'bland',
 'blend',
 'boiling',
 'boned',
 'boneless',
 'breast',
 'butt',
 'buy',
 'call',
 'called',
 'cheddar',
 'chilled',
 'choice',
 'chopped',
 'claw',
 'cleaned',
 'coarsely',
 'cold',
 'commonly',
 'cook',
 'cooked',
 'cored',
 'could',
 'country',
 'crushed',
 'crystal',
 'crystallized',
 'cut',
 'dairy',
 'deveined',
 'diced',
 'divided',
 'drained',
 'dried',
 'dry',
 'enough',
 'essence',
 'etc',
 'farfalle',
 'farmer',
 'fashioned',
 'fat',
 'favorite',
 'feel',
 'figure',
 'fine',
 'finely',
 'flaked',
 'flesh',
 'free',
 'french',
 'fresco',
 'fresh',
 'freshly',
 'frozen',
 'furikake',
 'garbanzo',
 'gardein',
 'garnish',
 'generic',
 'glove',
 'grand',
 'grape',
 'grated',
 'greek',
 'ground',
 'half',
 'halved',
 'help',
 'high',
 'hot',
 'http',
 'including',
 'indonesian',
 'italian',
 'jack',
 'japanese',
 'juice',
 'keep',
 'kikkoman',
 'large',
 'lea',
 'leafy',
 'lean',
 'leg',
 'lenghtwise',
 'length',
 'lengthwise',
 'like',
 'lite',
 'low',
 'lower',
 'made',
 'maggi',
 'marinade',
 'marron',
 'may',
 'meal',
 'meaty',
 'medium',
 'melted',
 'mexican',
 'mexico',
 'mild',
 'minced',
 'mine',
 'mix',
 'mixed',
 'mixture',
 'natural',
 'new',
 'non',
 'nonfat',
 'noodle',
 'nutritional',
 'oelek',
 'old',
 'one',
 'option',
 'optional',
 'pea',
 'peeled',
 'per',
 'perrins',
 'pickled',
 'place',
 'plus',
 'pollock',
 'powdered',
 'preferably',
 'prepared',
 'preserved',
 'processed',
 'protein',
 'quartered',
 'quatered',
 'queso',
 'quick',
 'red',
 'reduced',
 'regular',
 'remove',
 'removed',
 'rendered',
 'reserved',
 'rib',
 'ripe',
 'roasted',
 'room',
 'roughly',
 'salted',
 'scraped',
 'seasoned',
 'seaweed',
 'seed',
 'seeded',
 'seedless',
 'sesame',
 'sharp',
 'shelled',
 'short',
 'shredded',
 'skinless',
 'sliced',
 'small',
 'smoked',
 'sodium',
 'sour',
 'split',
 'starch',
 'stewed',
 'strip',
 'style',
 'substitute',
 'sweetened',
 'taste',
 'temperature',
 'thawed',
 'thick',
 'thin',
 'thinly',
 'toasted',
 'top',
 'topping',
 'unavailable',
 'uncooked',
 'unpeeled',
 'unsalted',
 'unsmoked',
 'unsweetened',
 'use',
 'used',
 'using',
 'veggie',
 'warm',
 'washed',
 'wear',
 'wedge',
 'whipped',
 'white',
 'wing',
 'without',
 'yabbies'}

In [53]:
if "refrigerated" in redund:
    print("true")

else:
    print("false")

false

FUNCTIONS FOR PREPROCESSING

In [49]:
import re

def manipulate_string(input_string):
    # Remove special characters except for specific cases
    #modified_string = re.sub(r'[^a-zA-Z0-9*%&+/]', '', input_string)
    
    # Replace % if preceded by a number
    # modified_string = re.sub(r'(\d)%', r'\1%', input_string)

    # Remove % is not preceded by a number
    modified_string = re.sub(r'(?<!\d)%', '', input_string)
    
    # Replace & with 'and'
    modified_string = modified_string.replace('&', ' and ')
    
    # Replace + with 'plus'
    modified_string = modified_string.replace('+', ' plus ')
    
    # Replace / if it is between digits
    modified_string = re.sub(r"(?<![0-9])/|/(?![0-9])", " ", modified_string)
    
    # Replace - with 'to' if it is between digits
    modified_string = re.sub(r'(\d)-(\d)', r'\1 to \2', modified_string)
    modified_string = re.sub(r"(?<![0-9])-|-(?![0-9])", " ", modified_string)

    # Remove brackets
    modified_string = re.sub(r'[\(\)\[\]\{\}]', '', modified_string)
    
    return modified_string

In [54]:
english_stopwords = stopwords.words('english')

if "bottle" in english_stopwords:
    print("'' is included in the list of English stopwords.")
else:
    print("'packages' is not included in the list of English stopwords.")

'packages' is not included in the list of English stopwords.

In [55]:
def preprocess(text):

    # Replace for special cases
    text = text.replace('half a', '1/2')
    text = text.replace('half of', '1/2')
    text = text.replace('half from', '1/2')

    # Special character removal
    text = manipulate_string(text)
    
    # Tokenization
    tokens = word_tokenize(text)

    # join back %
    modified_list = []
    for i, item in enumerate(tokens):
        if i > 0 and item == "%":
            modified_list[-1] += item
        else:
            modified_list.append(item)
    
    # Convert to lowercase
    tokens = [token.lower() for token in modified_list]
    
    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    stop_words.remove('to')
    stop_words.remove('and')
    stop_words.remove('can')
    tokens = [token for token in tokens if token not in stop_words]
    tokens = [token for token in tokens if token not in redund]


    # Lemmatizing
    lemmer = WordNetLemmatizer()

    tokens = [lemmer.lemmatize(token) for token in tokens]

    return tokens

In [56]:
lemmer1 = WordNetLemmatizer()
print(lemmer1.lemmatize('m'))

m

Testing

In [57]:
for i in range(20):
    print(preprocess(structing.input[i]))

['1/2', 'sweet', 'onion', ',']
['6', 'ounce', 'mushroom', ',']
['4', 'corn', 'tortilla']
['1', '9', 'refrigerated', 'ounce', 'package', 'cheese', 'tortellini']
['2', 'tablespoon', 'basil', 'leaf']
['3/4', 'cup', 'sugar']
['2', 'tablespoon', 'extra', 'virgin', 'olive', 'oil']
['1', 'tomato', ',']
['2', '8', 'refrigerated', 'ounce', 'can', 'crescent', 'roll']
['6', '6', 'ounce', 'tilapia', 'fillet']
['1', '1/2', 'teaspoon', 'curry', 'powder']
['1', 'tablespoon', 'worcestershire', 'sauce']
['3', 'clove', 'garlic', ',']
['1/3', 'cup', 'orange']
['1/2', 'cup', 'onion', ',', 'to']
['2', '1.5', 'fluid', 'ounce', 'jigger', 'banana', 'liqueur']
['3/4', 'cup', 'mozzarella', 'cheese']
['4', '4', 'ounce', 'fillet', 'salmon', ',', 'skin']
['1', 'cup', 'vegetable', 'oil']
['1', '1', 'pound', 'inch', 'green', 'bean', ',', 'piece']

In [58]:
for i in range(20):
    arr = preprocess(structing.input[i])
            
    int_mul = 0
    mul_idx = 0
    
    int_frac = 0
    start_frac_idx = 0
    end_frac_idx = 0
    
    final_string = ''
    for m in range(len(arr)):        
        if '/' in arr[m]:
            try:
                int_frac = int(arr[m-1]) + (int(arr[m].split('/')[0]) / int(arr[m].split('/')[1]))   
                start_frac_idx = m-1
                end_frac_idx = m
            except Exception as e:
                int_frac = int(arr[m].split('/')[0]) / int(arr[m].split('/')[1])
                start_frac_idx = m
                end_frac_idx = m
                pass
        try:
            int_mul = int(arr[m-1]) * int(arr[m])
        except Exception as e:
            pass
        
        if (int_frac != 0):
            final_string = final_string[:len(final_string)-2] + '{:.2f}'.format(int_frac) + final_string[len(final_string)+1:] + ' ' 
            int_frac = 0                
        elif (int_mul != 0):
            final_string = final_string[:len(final_string)-2] + str(int_mul) + final_string[len(final_string)+1:] + ' ' 
            int_mul = 0
        else:
            final_string += arr[m] + ' '        
    print(final_string)

0.50 sweet onion ,
6 ounce mushroom ,
4 corn tortilla
9 refrigerated ounce package cheese tortellini
2 tablespoon basil leaf
0.75 cup sugar
2 tablespoon extra virgin olive oil
1 tomato ,
16 refrigerated ounce can crescent roll
36 ounce tilapia fillet
1.50 teaspoon curry powder
1 tablespoon worcestershire sauce
3 clove garlic ,
0.33 cup orange
0.50 cup onion , to
2 1.5 fluid ounce jigger banana liqueur
0.75 cup mozzarella cheese
16 ounce fillet salmon , skin
1 cup vegetable oil
1 pound inch green bean , piece

The Real Thing

In [59]:
structing['input_pre'] = structing['input'].apply(preprocess)
structing

,index,input,name,qty,range_end,unit,comment,input_pre
0,0,"1/2 large sliced sweet red onion , thinly",sweet red onion,1/2,0,NaN,"large sliced , thinly","[1/2, sweet, onion, ,]"
1,1,"6 fresh sliced ounces mushrooms ,",mushrooms,6,0,ounces,"fresh sliced ,","[6, ounce, mushroom, ,]"
2,2,4 corn tortillas,corn tortillas,4,0,NaN,NaN,"[4, corn, tortilla]"
3,3,1 9 refrigerated ounce package cheese tortelli...,cheese tortellini,1 9,0,ounce package,refrigerated ( ),"[1, 9, refrigerated, ounce, package, cheese, t..."
4,4,2 fresh chopped tablespoons basil leaves,basil leaves,2,0,tablespoons,fresh chopped,"[2, tablespoon, basil, leaf]"
...,...,...,...,...,...,...,...,...
2174,2174,3/4 powdered lb sugar ( Add more if icing is t...,sugar,3/4,0,lb,powdered ( Add more if icing is too thin ),"[3/4, lb, sugar, icing]"
2175,2175,1 teaspoon tender thyme leaves,tender thyme leaves,1,0,teaspoon,NaN,"[1, teaspoon, tender, thyme, leaf]"
2176,2176,1 fresh chopped tablespoon parsley leaves,parsley leaves,1,0,tablespoon,fresh chopped,"[1, tablespoon, parsley, leaf]"
2177,2177,1 cup Russian salad dressing ( bottled is ok t...,Russian salad,1,0,cup,dressing ( bottled is ok too ),"[1, cup, russian, salad, dressing, bottled, ok]"
2178,2178,1 sprig celery leaves,celery leaves,1,0,sprig,NaN,"[1, sprig, celery, leaf]"

Extracting measurement units

In [60]:
structing['input_pre'][363]

['1', 'tablespoon', 'cilantro', ',', 'to']

In [61]:
def extract_units(structing,measure):
    extract={}
    measure_dic={"jar","can","packet","package","box","bottle","container", "jars","cans","packets","packages","boxes","bottles","containers","jarred","canned","packaged","bottled","conatined","boxed"}
    count = {}
    texts=structing['input_pre']
    
    start = 0
    flag = True

    for k in range(len(texts)):
        for a in range(len(texts[k])):
            
            if texts[k][a] in measure and texts[k][a] != "": 
                extract[a] = texts[k][a]
               
        
        ele = ''
        for i in extract:
            if extract[i] in measure_dic:
                continue
            else:
                flag = False
                ele = extract[i]
                break
                
                
        if flag == False:
            count = 0
            for i in extract:
                #print("before ", texts[k])
                texts[k].pop(i-count)
                count = count +1
                #print("after ", texts[k])
                
          
            texts[k].insert(list(extract.keys())[0] , ele)
                
        
        flag= True
        extract = {}
        #print(texts[k])
    return texts

In [62]:
text=extract_units(structing,measure)
structing['input_pre']= text
print(structing['input_pre'])

0                                [1/2, sweet, onion, ,]
1                               [6, ounce, mushroom, ,]
2                                   [4, corn, tortilla]
3       [1, 9, refrigerated, ounce, cheese, tortellini]
4                                [2, tablespoon, basil]
                             ...
2174                            [3/4, lb, sugar, icing]
2175                       [1, teaspoon, tender, thyme]
2176                           [1, tablespoon, parsley]
2177             [1, cup, russian, salad, dressing, ok]
2178                                 [1, sprig, celery]
Name: input_pre, Length: 2179, dtype: object

– ”clove” and ”garlic”;

– ”stick” and ”butter”/”margarine”/”cinnamon”/ ”car-rot”/”celery”;

– ”sprig” and ”rosemary”/”thyme”/”mint”/”parsley”; – ”link” and ”sausage”;

– ”stalk” and ”celery”/”green onion”/”spring onion”/”broccoli”/”kale”/”cauliflower”;

– ”sheet” and ”gelatin”;

– ”cube” and ”stock”/”butter”,”margarine”;

– ”head” and ”cabbage”/”lettuce”/”cauliflower”;

In [63]:
for i in range(20):
    arr = preprocess(structing.input[i])
            
    int_mul = 0
    mul_idx = 0
    
    int_frac = 0
    start_frac_idx = 0
    end_frac_idx = 0
    
    measurements = []  # List to store extracted measurements
    
    final_string = ''
    for m in range(len(arr)):
        # Check if the element is a fraction
        if '/' in arr[m]:
            try:
                int_frac = int(arr[m-1]) + (int(arr[m].split('/')[0]) / int(arr[m].split('/')[1]))   
                start_frac_idx = m-1
                end_frac_idx = m
            except Exception as e:
                int_frac = int(arr[m].split('/')[0]) / int(arr[m].split('/')[1])
                start_frac_idx = m
                end_frac_idx = m
                pass
        
        # Check if the elements form a multiplication
        try:
            int_mul = int(arr[m-1]) * int(arr[m])
        except Exception as e:
            pass
        
        # Check if the element is a measurement unit
        if arr[m] in measure:
            measurements.append( arr[m])
        
        # Generate the final string
        if int_frac != 0:
            final_string = final_string[:len(final_string)-2] + '{:.2f}'.format(int_frac) + final_string[len(final_string)+1:] + ' ' 
            int_frac = 0                
        elif int_mul != 0:
            final_string = final_string[:len(final_string)-2] + str(int_mul) + final_string[len(final_string)+1:] + ' ' 
            int_mul = 0
        else:
            final_string += arr[m] + ' '
    
    print("Final String:", final_string)
    print("Measurements:", measurements)

Final String: 0.50 sweet onion ,
Measurements: []
Final String: 6 ounce mushroom ,
Measurements: ['ounce']
Final String: 4 corn tortilla
Measurements: []
Final String: 9 refrigerated ounce package cheese tortellini
Measurements: ['ounce', 'package']
Final String: 2 tablespoon basil leaf
Measurements: ['tablespoon', 'leaf']
Final String: 0.75 cup sugar
Measurements: ['cup']
Final String: 2 tablespoon extra virgin olive oil
Measurements: ['tablespoon']
Final String: 1 tomato ,
Measurements: []
Final String: 16 refrigerated ounce can crescent roll
Measurements: ['ounce', 'can']
Final String: 36 ounce tilapia fillet
Measurements: ['ounce']
Final String: 1.50 teaspoon curry powder
Measurements: ['teaspoon']
Final String: 1 tablespoon worcestershire sauce
Measurements: ['tablespoon']
Final String: 3 clove garlic ,
Measurements: ['clove']
Final String: 0.33 cup orange
Measurements: ['cup']
Final String: 0.50 cup onion , to
Measurements: ['cup']
Final String: 2 1.5 fluid ounce jigger banana liqueur
Measurements: ['ounce', 'jigger']
Final String: 0.75 cup mozzarella cheese
Measurements: ['cup']
Final String: 16 ounce fillet salmon , skin
Measurements: ['ounce']
Final String: 1 cup vegetable oil
Measurements: ['cup']
Final String: 1 pound inch green bean , piece
Measurements: ['pound', 'inch', 'piece']

In [64]:

for i in range(20):
    arr = preprocess(structing.input[i])
            
    int_mul = 0
    mul_idx = 0
    
    int_frac = 0
    start_frac_idx = 0
    end_frac_idx = 0
    
    measurements = []  # List to store extracted measurements
    
    final_string = ''
    for m in range(len(arr)):
        # Check if the element is a fraction
        if '/' in arr[m]:
            try:
                int_frac = int(arr[m-1]) + (int(arr[m].split('/')[0]) / int(arr[m].split('/')[1]))   
                start_frac_idx = m-1
                end_frac_idx = m
            except Exception as e:
                int_frac = int(arr[m].split('/')[0]) / int(arr[m].split('/')[1])
                start_frac_idx = m
                end_frac_idx = m
                pass
        
        # Check if the elements form a multiplication
        try:
            int_mul = int(arr[m-1]) * int(arr[m])
        except Exception as e:
            pass
        
        # Check if the element is a measurement unit
        if arr[m] in measure:
            measurements.append(arr[m])
        
        # Generate the final string
        if int_frac != 0:
            final_string = final_string[:len(final_string)-2] + '{:.2f}'.format(int_frac) + final_string[len(final_string)+1:] + ' ' 
            int_frac = 0                
        elif int_mul != 0:
            final_string = final_string[:len(final_string)-2] + str(int_mul) + final_string[len(final_string)+1:] + ' ' 
            int_mul = 0
        else:
            final_string += arr[m] + ' '
    
    # Extract the food item
    food_item = final_string.lower()
    for word in redund:
        if word in food_item.split():
            food_item = food_item.replace(word, '')
    
    # Special cases for certain measurement units considered as food items
    special_units = {"jar","can","packet","package","box","bottle","container", "jars","cans","packets","packages","boxes","bottles","containers","canned","bottled","packed","packaged","jarred","boxed","contained"}
    for unit in special_units:
        if unit in food_item.split():
            if len(measurements) == 0 or any(unit in m for m in measurements):
                food_item = food_item.replace(unit, '')
            else:
                measurements.append(unit)
    
    food_item = ' '.join(food_item.split())  # Remove extra whitespace
    
    print("Final String:", final_string)
    print("Measurements:", measurements)
    print("Food Item:", food_item.strip())

Final String: 0.50 sweet onion ,
Measurements: []
Food Item: 0.50 sweet onion ,
Final String: 6 ounce mushroom ,
Measurements: ['ounce']
Food Item: 6 ounce mushroom ,
Final String: 4 corn tortilla
Measurements: []
Food Item: 4 corn tortilla
Final String: 9 refrigerated ounce package cheese tortellini
Measurements: ['ounce', 'package']
Food Item: 9 refrigerated ounce cheese tortellini
Final String: 2 tablespoon basil leaf
Measurements: ['tablespoon', 'leaf']
Food Item: 2 tablespoon basil leaf
Final String: 0.75 cup sugar
Measurements: ['cup']
Food Item: 0.75 cup sugar
Final String: 2 tablespoon extra virgin olive oil
Measurements: ['tablespoon']
Food Item: 2 tablespoon extra virgin olive oil
Final String: 1 tomato ,
Measurements: []
Food Item: 1 tomato ,
Final String: 16 refrigerated ounce can crescent roll
Measurements: ['ounce', 'can']
Food Item: 16 refrigerated ounce crescent roll
Final String: 36 ounce tilapia fillet
Measurements: ['ounce']
Food Item: 36 ounce tilapia fillet
Final String: 1.50 teaspoon curry powder
Measurements: ['teaspoon']
Food Item: 1.50 teaspoon curry powder
Final String: 1 tablespoon worcestershire sauce
Measurements: ['tablespoon']
Food Item: 1 tablespoon worcestershire sauce
Final String: 3 clove garlic ,
Measurements: ['clove']
Food Item: 3 clove garlic ,
Final String: 0.33 cup orange
Measurements: ['cup']
Food Item: 0.33 cup orange
Final String: 0.50 cup onion , to
Measurements: ['cup']
Food Item: 0.50 cup onion , to
Final String: 2 1.5 fluid ounce jigger banana liqueur
Measurements: ['ounce', 'jigger']
Food Item: 2 1.5 fluid ounce jigger banana liqueur
Final String: 0.75 cup mozzarella cheese
Measurements: ['cup']
Food Item: 0.75 cup mozzarella cheese
Final String: 16 ounce fillet salmon , skin
Measurements: ['ounce']
Food Item: 16 ounce fillet salmon , skin
Final String: 1 cup vegetable oil
Measurements: ['cup']
Food Item: 1 cup vegetable oil
Final String: 1 pound inch green bean , piece
Measurements: ['pound', 'inch', 'piece']
Food Item: 1 pound inch green , piece

In [103]:

for i in range(20):
    arr = preprocess(structing.input[i])
            
    int_mul = 0
    mul_idx = 0
    
    int_frac = 0
    start_frac_idx = 0
    end_frac_idx = 0
    
    measurements = []  # List to store extracted measurements
    quantity=''
    
    final_string = ''
    for m in range(len(arr)):
        # Check if the element is a fraction
        if '/' in arr[m]:
            try:
                int_frac = int(arr[m-1]) + (int(arr[m].split('/')[0]) / int(arr[m].split('/')[1]))   
                start_frac_idx = m-1
                end_frac_idx = m
            except Exception as e:
                int_frac = int(arr[m].split('/')[0]) / int(arr[m].split('/')[1])
                start_frac_idx = m
                end_frac_idx = m
                pass
        
        # Check if the elements form a multiplication
        try:
            int_mul = int(arr[m-1]) * int(arr[m])
        except Exception as e:
            pass
        split_string = final_string.split()

        # Check if the element is a measurement unit
        if arr[m] in measure:
            measurements.append(arr[m])
        if len(split_string) > 1:
            unit = split_string[1]

        
        # Generate the final string
        if int_frac != 0:
            final_string = final_string[:len(final_string)-2] + '{:.2f}'.format(int_frac) + final_string[len(final_string)+1:] + ' ' 
            int_frac = 0                
        elif int_mul != 0:
            final_string = final_string[:len(final_string)-2] + str(int_mul) + final_string[len(final_string)+1:] + ' ' 
            int_mul = 0
        else:
            final_string += arr[m] + ' '
    
    # Extract the food item
    food_item = final_string.lower()
    for word in redund:
        if word in food_item.split():
            food_item = food_item.replace(word, '')
    
    # Special cases for certain measurement units considered as food items
    special_units = {"jar","can","packet","package","box","bottle","container", "jars","cans","packets","packages","boxes","bottles","containers","canned","bottled","packed","packaged","jarred","boxed","contained"}
    for unit in special_units:
        if unit in food_item.split():
            if len(measurements) == 0 or any(unit in m for m in measurements):
                food_item = food_item.replace(unit, '')
            else:
                measurements.append(unit)
    
    #food_item = ' '.join(food_item.split())  # Remove extra whitespace
    
    # Extracting exactly one quantity, one unit of measurement, and one food item
    unit = measurements.pop(0) if len(measurements) > 0 else ""
    words = final_string.split()

    if words[0].replace(".", "").isdigit():
        quantity = words[0]

    # Remove the quantity from the line
    food_item = final_string.replace(quantity, "")

# Remove leading and trailing whitespace
    food_item = food_item.strip()
    if len(split_string) > 2:
        food_item = " ".join(split_string[2:])


    
    print("Final String:", final_string)
    print("Quantity:", quantity)
    print("Unit:", unit)
    print("Food Item:", food_item)
    print()


    # Define the CSV file path

Final String: 0.50 sweet onion ,
Quantity: 0.50
Unit:
Food Item: onion

Final String: 6 ounce mushroom ,
Quantity: 6
Unit: ounce
Food Item: mushroom

Final String: 4 corn tortilla
Quantity: 4
Unit:
Food Item: corn tortilla

Final String: 9 refrigerated ounce package cheese tortellini
Quantity: 9
Unit: ounce
Food Item: ounce package cheese

Final String: 2 tablespoon basil leaf
Quantity: 2
Unit: tablespoon
Food Item: basil

Final String: 0.75 cup sugar
Quantity: 0.75
Unit: cup
Food Item: cup sugar

Final String: 2 tablespoon extra virgin olive oil
Quantity: 2
Unit: tablespoon
Food Item: extra virgin olive

Final String: 1 tomato ,
Quantity: 1
Unit:
Food Item: tomato ,

Final String: 16 refrigerated ounce can crescent roll
Quantity: 16
Unit: ounce
Food Item: ounce can crescent

Final String: 36 ounce tilapia fillet
Quantity: 36
Unit: ounce
Food Item: tilapia

Final String: 1.50 teaspoon curry powder
Quantity: 1.50
Unit: teaspoon
Food Item: curry

Final String: 1 tablespoon worcestershire sauce
Quantity: 1
Unit: tablespoon
Food Item: worcestershire

Final String: 3 clove garlic ,
Quantity: 3
Unit: clove
Food Item: garlic

Final String: 0.33 cup orange
Quantity: 0.33
Unit: cup
Food Item: cup orange

Final String: 0.50 cup onion , to
Quantity: 0.50
Unit: cup
Food Item: onion ,

Final String: 2 1.5 fluid ounce jigger banana liqueur
Quantity: 2
Unit: ounce
Food Item: fluid ounce jigger banana

Final String: 0.75 cup mozzarella cheese
Quantity: 0.75
Unit: cup
Food Item: mozzarella

Final String: 16 ounce fillet salmon , skin
Quantity: 16
Unit: ounce
Food Item: fillet salmon ,

Final String: 1 cup vegetable oil
Quantity: 1
Unit: cup
Food Item: vegetable

Final String: 1 pound inch green bean , piece
Quantity: 1
Unit: pound
Food Item: inch green bean ,

In [104]:
import csv

# Create a CSV file and write the headers
with open('extracted_data.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['Final String', 'Quantity', 'Unit', 'Food Item'])

    for i in range(20):
        arr = preprocess(structing.input[i])
                
        int_mul = 0
        mul_idx = 0
        
        int_frac = 0
        start_frac_idx = 0
        end_frac_idx = 0
        
        measurements = []  # List to store extracted measurements
        quantity = ''
        
        final_string = ''
        for m in range(len(arr)):
            # Check if the element is a fraction
            if '/' in arr[m]:
                try:
                    int_frac = int(arr[m-1]) + (int(arr[m].split('/')[0]) / int(arr[m].split('/')[1]))   
                    start_frac_idx = m-1
                    end_frac_idx = m
                except Exception as e:
                    int_frac = int(arr[m].split('/')[0]) / int(arr[m].split('/')[1])
                    start_frac_idx = m
                    end_frac_idx = m
                    pass
            
            # Check if the elements form a multiplication
            try:
                int_mul = int(arr[m-1]) * int(arr[m])
            except Exception as e:
                pass
            split_string = final_string.split()
    
            # Check if the element is a measurement unit
            if arr[m] in measure:
                measurements.append(arr[m])
            if len(split_string) > 1:
                unit = split_string[1]
    
            
            # Generate the final string
            if int_frac != 0:
                final_string = final_string[:len(final_string)-2] + '{:.2f}'.format(int_frac) + final_string[len(final_string)+1:] + ' ' 
                int_frac = 0                
            elif int_mul != 0:
                final_string = final_string[:len(final_string)-2] + str(int_mul) + final_string[len(final_string)+1:] + ' ' 
                int_mul = 0
            else:
                final_string += arr[m] + ' '
        
        # Extract the food item
        food_item = final_string.lower()
        for word in redund:
            if word in food_item.split():
                food_item = food_item.replace(word, '')
        
        # Special cases for certain measurement units considered as food items
        special_units = {"jar","can","packet","package","box","bottle","container", "jars","cans","packets","packages","boxes","bottles","containers","canned","bottled","packed","packaged","jarred","boxed","contained"}
        for unit in special_units:
            if unit in food_item.split():
                if len(measurements) == 0 or any(unit in m for m in measurements):
                    food_item = food_item.replace(unit, '')
                else:
                    measurements.append(unit)
        
        #food_item = ' '.join(food_item.split())  # Remove extra whitespace
        
        # Extracting exactly one quantity, one unit of measurement, and one food item
        unit = measurements.pop(0) if len(measurements) > 0 else ""
        words = final_string.split()
    
        if words[0].replace(".", "").isdigit():
            quantity = words[0]
    
        # Remove the quantity from the line
        food_item = final_string.replace(quantity, "")
    
        # Remove leading and trailing whitespace
        food_item = food_item.strip()
        if len(split_string) > 2:
            food_item = " ".join(split_string[2:])
        
        # Write the extracted data to the CSV file
        writer.writerow([final_string, quantity, unit, food_item])

# Print a message indicating the successful creation of the CSV file
print("CSV file 'extracted_data.csv' has been created.")

CSV file 'extracted_data.csv' has been created.